coverage:
  precision: 2
  round: down
  range: '80...100'
  status:
    project:
      default:
        target: auto
      css-processor:
        target: auto
        flags:
          - css-processor
      transient-render-engine:
        target: auto
        flags:
          - transient-render-engine
      render-html:
        target: auto
        flags:
          - render-html

flags:
  css-processor:
    paths:
      - packages/css-processor/
  transient-render-engine:
    paths:
      - packages/transient-render-engine/
  render-html:
    paths:
      - packages/render-html/
