coverage:
  precision: 2
  round: down
  range: '55...95'
  status:
    ersatz:
      flags:
        - ersatz

flags:
  css-processor:
    paths:
      - packages/css-processor/coverage/cover.xml
  transient-render-tree:
    paths:
      - packages/transient-render-tree/coverage/cover.xml
