coverage:
  precision: 2
  round: down
  range: '80...100'
  status:
    project:
      default:
        target: auto
      css-processor:
        target: auto
        flags:
          - css-processor
      transient-render-engine:
        target: auto
        flags:
          - transient-render-engine

flags:
  css-processor:
    paths:
      - packages/css-processor/coverage/cover.xml
  transient-render-engine:
    paths:
      - packages/transient-render-engine/coverage/cover.xml
