# This workflow will do a clean install of node dependencies, run JS and Typescript tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# This workflow will do a clean install of node dependencies, run JS and Typescript tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: transient-render-engine

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --immutable
    - run: yarn build:css-processor
      name: Build dependencies
    - run: yarn test:transient-render-engine:ts
      name: Typescript Tests
    - run: yarn run test:transient-render-engine:lint
      name: Linting Tests
    - run: yarn run test:transient-render-engine:jest --coverage
      name: Behavior Tests
    - run: yarn build:transient-render-engine
      name: Build
    - uses: codecov/codecov-action@v2
      with:
        flags: transient-render-engine
        fail_ci_if_error: false
